### ISSUE TITLE
Add more implementations

### ISSUE THREAD

**Issue by jackdevey** [russellbanks/BubbleSorts#1]
Please consider:
- ArnoldC
- R
- TypeScript
- C
- C++
- C#
- F#
- Scala
- Dart
- x86 Assembly 
- DinkC
- TI Script

:)

**Comment by russellbanks** [comment]
Thank you for these suggestions ❤️

I hope to do all off these languages eventually, but as you can imagine, I'm not exactly fluent in every possible language so most of these implementations that I write are a learning experience for me, too. Therefore, I will do them, but some will be prioritised over others as they are easier to do or have more materials to learn with.

I'll reference this issue whenever I add any of these languages 😄

**Comment by jackdevey** [comment]
Rip this issue :(

**Comment by russellbanks** [comment]
Sorry @jackdevey, this was a fun project to do, but I can't commit the time to add all of them currently. I would direct you to the [TheAlgorithms](https://github.com/TheAlgorithms) repository for your language of choice. Each repository should have a directory for sorting algorithms. For example, [TheAlgorithms/Python/sorts](https://github.com/TheAlgorithms/Python/tree/master/sorts).

**Comment by jackdevey** [comment]
alr lad
